server:
  port: 8085

spring:
  mail:
    host: smtp.gmail.com
    port: 465 # Switch to SSL port for Railway
    username: nithika151@gmail.com
    password: enxmsnsomcagxwrz # Your 16-character App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false # Disable StartTLS when using Port 465
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory # Forces SSL connection

services:
  identity-url: ${IDENTITY_SERVICE_URL:https://user-identity-service.onrender.com}
  order-url: ${ORDER_SERVICE_URL:https://order-service-production-5615.up.railway.app}
  payment-url: ${PAYMENT_SERVICE_URL:https://food-order-payment-service-production.up.railway.app}