package com.foodsystem.notification_service.service;

import com.foodsystem.notification_service.dto.*;
import com.sendgrid.*;
import com.sendgrid.helpers.mail.Mail;
import com.sendgrid.helpers.mail.objects.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import java.io.IOException;

@Service
public class NotificationService {

    @Autowired private RestTemplate restTemplate;

    // SendGrid API Key from Environment Variables
    @Value("${sendgrid.api-key}") 
    private String sendGridApiKey;

    // Your verified SendGrid sender email
    @Value("${spring.mail.username}") 
    private String senderEmail;

    @Value("${services.identity-url}") private String identityUrl;
    @Value("${services.payment-url}") private String paymentUrl;

    public void processNotification(NotificationRequest request) {
        try {
            String userUrl = identityUrl + "/api/users/" + request.getUserId();
            UserDTO user = restTemplate.getForObject(userUrl, UserDTO.class);

            String paymentUrlFull = paymentUrl + "/api/payments/order/" + request.getOrderId();
            System.out.println("Calling Payment Service: " + paymentUrlFull);

            PaymentResponse response = restTemplate.getForObject(paymentUrlFull, PaymentResponse.class);

            if (response != null && response.getData() != null) {
                PaymentDTO payment = response.getData();
                System.out.println("Fetched Amount: " + payment.getAmount());
                
                if (user != null) {
                    sendMeaningfulEmail(user, payment, request.getOrderId());
                }
            }
        } catch (Exception e) {
            System.err.println("Critical Integration Error: " + e.getMessage());
        }
    }

    private void sendMeaningfulEmail(UserDTO user, PaymentDTO payment, String orderId) {
    try {
        System.out.println("Generating Professional UI for: " + user.getEmail());
        
        Email from = new Email(senderEmail); // nithika151@gmail.com
        String subject = "Gourmet Express - Receipt for Order #" + orderId;
        Email to = new Email(user.getEmail());
        
        // Clean UI with Table for Instructor Review
        String htmlContent = "<html><body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>" +
            "<div style='max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd;'>" +
            "<h2 style='color: #d9534f; text-align: center;'>Gourmet Express Official Receipt</h2>" +
            "<hr>" +
            "<h3>1. Customer Profile (Fetched from Identity Service)</h3>" +
            "<p><b>Full Name:</b> " + user.getUsername() + "</p>" +
            "<p><b>Registered Email:</b> " + user.getEmail() + "</p>" +
            "<p><b>Delivery Address:</b> " + user.getDeliveryAddress() + "</p>" +
            "<hr>" +
            "<hr>" +
            "<h3>2. Transaction Details (Fetched from Payment Service)</h3>" +
            "<table style='width: 100%; border: 1px solid #eee; border-collapse: collapse;'>" +
            "  <tr style='background: #f8f9fa;'> <th style='padding: 8px; text-align: left;'>Field</th> <th style='padding: 8px; text-align: left;'>Value</th> </tr>" +
            "  <tr> <td style='padding: 8px; border-bottom: 1px solid #eee;'>Product Name</td> <td style='padding: 8px; border-bottom: 1px solid #eee;'>" + payment.getOrderDetails().getProduct() + "</td> </tr>" +
            "  <tr> <td style='padding: 8px; border-bottom: 1px solid #eee;'>Quantity</td> <td style='padding: 8px; border-bottom: 1px solid #eee;'>" + payment.getOrderDetails().getQuantity() + "</td> </tr>" +
            "  <tr> <td style='padding: 8px; border-bottom: 1px solid #eee;'>Payment Status</td> <td style='padding: 8px; border-bottom: 1px solid #eee; color: green;'><b>" + payment.getStatus().toUpperCase() + "</b></td> </tr>" +
            "  <tr> <td style='padding: 8px; border-bottom: 1px solid #eee;'><b>Total Amount</b></td> <td style='padding: 8px; border-bottom: 1px solid #eee;'><b>LKR " + payment.getAmount() + "</b></td> </tr>" +
            "</table>" +
            "<p style='margin-top: 20px; font-size: 12px; color: #888; text-align: center;'>" +
            "This notification was generated by the 5th Microservice (Notification Service) deployed on Render." +
            "<br>Integration Points: Render Identity Node & Railway Payment Node." +
            "</p>" +
            "</div></body></html>";

        Content content = new Content("text/html", htmlContent);
        Mail mail = new Mail(from, subject, to, content);
        SendGrid sg = new SendGrid(sendGridApiKey); //
        Request request = new Request();

        request.setMethod(Method.POST);
        request.setEndpoint("mail/send");
        request.setBody(mail.build());
        
        Response response = sg.api(request);
        System.out.println("SendGrid API Status: " + response.getStatusCode());
        System.out.println("SUCCESS: Comprehensive UI Email sent to " + user.getEmail());
        
    } catch (IOException ex) {
        System.err.println("API UI Error: " + ex.getMessage());
    }
}

    public void sendWelcomeEmail(Long userId) {
        try {
            String userUrl = identityUrl + "/api/users/" + userId;
            UserDTO user = restTemplate.getForObject(userUrl, UserDTO.class);

            if (user != null) {
                Email from = new Email(senderEmail);
                Email to = new Email(user.getEmail());
                Content content = new Content("text/plain", "Welcome to Gourmet Express, " + user.getUsername() + "!");
                Mail mail = new Mail(from, "Welcome!", to, content);

                SendGrid sg = new SendGrid(sendGridApiKey);
                Request request = new Request();
                request.setMethod(Method.POST);
                request.setEndpoint("mail/send");
                request.setBody(mail.build());
                sg.api(request);
            }
        } catch (Exception e) {
            System.err.println("Welcome Email API Error: " + e.getMessage());
        }
    }
}